07/29/2021 10:19:03 - INFO - __main__ - Config args: Namespace(append_another_bos=True, checkpoint='', dataset='mrqa_naturalquestions', debug=False, dev_file='', do_lowercase=False, do_predict=True, do_train=False, max_input_length=888, max_output_length=50, model='facebook/bart-base', num_beams=4, output_dir='out/mrqa_naturalquestions_bart-base_0617v4', predict_batch_size=64, predict_checkpoint='out/mrqa_naturalquestions_bart-base_0617v4/best-model.pt', prefix='', quiet=False, seed=42, train_file='')
07/29/2021 10:19:03 - INFO - __main__ - Config args: Namespace(append_another_bos=True, checkpoint='', dataset='mrqa_naturalquestions', debug=False, dev_file='', do_lowercase=False, do_predict=True, do_train=False, max_input_length=888, max_output_length=50, model='facebook/bart-base', num_beams=4, output_dir='out/mrqa_naturalquestions_bart-base_0617v4', predict_batch_size=64, predict_checkpoint='out/mrqa_naturalquestions_bart-base_0617v4/best-model.pt', prefix='', quiet=False, seed=42, train_file='')
Traceback (most recent call last):
  File "semanticdebugger/benchmark_gen/build_bugpool.py", line 115, in <module>
    main()
  File "semanticdebugger/benchmark_gen/build_bugpool.py", line 93, in main
    logger=logger, data_dist=args.data_dist)
  File "/private/home/yuchenlin/SemanticDebugger/semanticdebugger/benchmark_gen/bart_api.py", line 25, in inference_api
    logger, args, test_file, data_type="dev", is_training=False, task_name=args.dataset, data_dist=data_dist)
  File "/private/home/yuchenlin/SemanticDebugger/semanticdebugger/task_manager/dataloader.py", line 45, in __init__
    num_shards = torch.distributed.get_world_size() # the number of gpus
  File "/private/home/yuchenlin/.conda/envs/bartqa/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 584, in get_world_size
    return _get_group_size(group)
  File "/private/home/yuchenlin/.conda/envs/bartqa/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 200, in _get_group_size
    _check_default_pg()
  File "/private/home/yuchenlin/.conda/envs/bartqa/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 191, in _check_default_pg
    "Default process group is not initialized"
AssertionError: Default process group is not initialized
Traceback (most recent call last):
  File "semanticdebugger/benchmark_gen/build_bugpool.py", line 115, in <module>
    main()
  File "semanticdebugger/benchmark_gen/build_bugpool.py", line 93, in main
    logger=logger, data_dist=args.data_dist)
  File "/private/home/yuchenlin/SemanticDebugger/semanticdebugger/benchmark_gen/bart_api.py", line 25, in inference_api
    logger, args, test_file, data_type="dev", is_training=False, task_name=args.dataset, data_dist=data_dist)
  File "/private/home/yuchenlin/SemanticDebugger/semanticdebugger/task_manager/dataloader.py", line 45, in __init__
    num_shards = torch.distributed.get_world_size() # the number of gpus
  File "/private/home/yuchenlin/.conda/envs/bartqa/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 584, in get_world_size
    return _get_group_size(group)
  File "/private/home/yuchenlin/.conda/envs/bartqa/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 200, in _get_group_size
    _check_default_pg()
  File "/private/home/yuchenlin/.conda/envs/bartqa/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 191, in _check_default_pg
    "Default process group is not initialized"
AssertionError: Default process group is not initialized
Traceback (most recent call last):
  File "/private/home/yuchenlin/.conda/envs/bartqa/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/private/home/yuchenlin/.conda/envs/bartqa/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/private/home/yuchenlin/.conda/envs/bartqa/lib/python3.6/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/private/home/yuchenlin/.conda/envs/bartqa/lib/python3.6/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/private/home/yuchenlin/.conda/envs/bartqa/bin/python', '-u', 'semanticdebugger/benchmark_gen/build_bugpool.py', '--local_rank=0', '--data_dist', '--data_file', 'data/mrqa_naturalquestions/mrqa_naturalquestions_train.jsonl', '--bug_file', 'bug_data/mrqa_naturalquestions_train.bugs.jsonl', '--conig_file', 'scripts/infer_mrqa_bart_base.config', '--prefix', 'mrqa_naturalquestions_dev_bart-base_0617v4_build_bug']' returned non-zero exit status 1.
