10/14/2021 01:48:36 - INFO - __main__ - run_name = zany-durian-21
10/14/2021 01:48:36 - INFO - __main__ - Loading ['exp_results/supervision_data/1014_init_mean_dm_simple/dm.23-0.pkl', 'exp_results/supervision_data/1014_init_mean_dm_simple/dm.30-0.pkl', 'exp_results/supervision_data/1014_init_mean_dm_simple/dm.17-0.pkl', 'exp_results/supervision_data/1014_init_mean_dm_simple/dm.12-0.pkl', 'exp_results/supervision_data/1014_init_mean_dm_simple/dm.10-0.pkl', 'exp_results/supervision_data/1014_init_mean_dm_simple/dm.3-0.pkl', 'exp_results/supervision_data/1014_init_mean_dm_simple/dm.7-0.pkl', 'exp_results/supervision_data/1014_init_mean_dm_simple/dm.11-0.pkl', 'exp_results/supervision_data/1014_init_mean_dm_simple/dm.24-0.pkl', 'exp_results/supervision_data/1014_init_mean_dm_simple/dm.30-0.pkl']





loading pkl files:  60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                                | 6/10 [00:12<00:08,  2.16s/it]
Traceback (most recent call last):
  File "semanticdebugger/debug_algs/index_based/biencoder.py", line 41, in load_distant_supervision
    ds_items += pickle.load(f)
KeyboardInterrupt
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "semanticdebugger/debug_algs/index_based/biencoder.py", line 487, in <module>
    biencoder_args.ds_dir_path, sample_size=biencoder_args.num_ds_train_file, logger=logger, train_args=biencoder_args)
  File "semanticdebugger/debug_algs/index_based/biencoder.py", line 41, in load_distant_supervision
    ds_items += pickle.load(f)
